USE sistema_mantenimiento;

-- chofer
ALTER TABLE chofer
MODIFY COLUMN estado ENUM('ACTIVO', 'INACTIVO') DEFAULT 'ACTIVO';

-- usuario
ALTER TABLE usuario
MODIFY COLUMN rol ENUM('ADMINISTRADOR', 'SUPERVISOR') NOT NULL;

-- taller
ALTER TABLE taller
MODIFY COLUMN estado ENUM('ACTIVO', 'INACTIVO') DEFAULT 'ACTIVO';

-- vehiculo
ALTER TABLE vehiculo
MODIFY COLUMN estado_vehiculo ENUM('ACTIVO', 'INACTIVO', 'MANTENIMIENTO') DEFAULT 'ACTIVO',
MODIFY COLUMN tipo_combustible ENUM('GASOLINA', 'DIESEL', 'ELECTRICO', 'HIBRIDO', 'OTRO'),
MODIFY COLUMN tipo_vehiculo ENUM('SEDAN', 'SUV', 'CAMIONETA', 'VAN', 'CAMION', 'OTRO') NOT NULL;

-- tipo_mantenimiento
ALTER TABLE tipo_mantenimiento
MODIFY COLUMN categoria ENUM('PREVENTIVO', 'CORRECTIVO') NOT NULL,
MODIFY COLUMN prioridad ENUM('BAJA', 'MEDIA', 'ALTA');

-- alerta_mantenimiento
ALTER TABLE alerta_mantenimiento
MODIFY COLUMN tipo_alerta ENUM('PREVENTIVA', 'CORRECTIVA') DEFAULT 'PREVENTIVA',
MODIFY COLUMN estado_alerta ENUM('NOTIFICADA', 'ATENDIDA', 'VENCIDA') DEFAULT 'NOTIFICADA';

-- mantenimiento
ALTER TABLE mantenimiento
MODIFY COLUMN estado ENUM('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO') DEFAULT 'PENDIENTE';

-- servicio
ALTER TABLE servicio
MODIFY COLUMN estado ENUM('ACTIVO', 'INACTIVO') DEFAULT 'ACTIVO';
